import { PlaceHolderImages } from './placeholder-images';

export interface ProfileBackground {
  id: string;
  name: string;
  imageUrl: string;
}

// IDs for the predefined background images stored in placeholder-images.json
const backgroundIds = [
  'profile-bg-cyberpunk-red',
  'profile-bg-neon-grid',
  'profile-bg-dark-tech',
  'profile-bg-glitch-red',
];

/**
 * Predefined background options available for user profiles.
 * This array is generated by mapping over the backgroundIds, finding the corresponding
 * image data in PlaceHolderImages, and creating a descriptive name.
 */
export const predefinedBackgrounds: ProfileBackground[] = backgroundIds.map(id => {
  const image = PlaceHolderImages.find(img => img.id === id);
  // Creates a user-friendly name from the ID, e.g., 'profile-bg-neon-grid' -> 'Neon Grid'
  let name = id.replace('profile-bg-', '').replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  if (id === 'profile-bg-cyberpunk-red') name = "Cyberpunk Red";
  
  return {
    id,
    name,
    imageUrl: image?.imageUrl || '', // Fallback to an empty string if an image isn't found
  }
}).filter(bg => bg.imageUrl); // Ensure we only return backgrounds that have a valid image URL

// Sets the default background for new users or as a fallback.
export const defaultBackground = predefinedBackgrounds.length > 0 ? predefinedBackgrounds[0] : null;
