
import type { SystemPart } from './types';

/**
 * Data for the System Unit Parts Viewer.
 * Each part includes an ID, name, description, installation notes,
 * and its position on the main system unit image (photo-1624705002806-5d72df19c3ad).
 */
export const systemPartsData: SystemPart[] = [
  {
    id: 'motherboard',
    name: 'Motherboard (Main Circuit Board)',
    description: 'The foundation of the PC. It houses the Chipset, which determines the features and compatibility of the system. Key specs to note: Form Factor (ATX, mATX, ITX) and Socket Type.',
    installation: 'Mount using brass standoffs to prevent electrical shorts against the chassis. Ensure the I/O shield is snapped into the case before lowering the board.',
    position: { top: '45%', left: '45%', width: '45%', height: '65%' },
  },
  {
    id: 'cpu',
    name: 'CPU (The Brain)',
    description: 'The Central Processing Unit executes every command. Speed is measured in GHz (Gigahertz). Modern CPUs have multiple cores for multitasking.',
    installation: 'Place carefully into the socket matching the triangle markers. Lower the retention arm. Always apply a pea-sized amount of thermal paste.',
    position: { top: '35%', left: '42%', width: '12%', height: '12%' },
  },
  {
    id: 'cpu-cooler',
    name: 'CPU Thermal Management',
    description: 'Essential for dissipating the intense heat generated by the processor. Can be Air-cooled (heatsink/fan) or Liquid-cooled (AIO).',
    installation: 'Ensure firm and even pressure over the CPU. Plug the fan header into the "CPU_FAN" connector on the motherboard to allow BIOS speed control.',
    position: { top: '32%', left: '40%', width: '20%', height: '20%' },
  },
  {
    id: 'ram',
    name: 'RAM (Short-Term Memory)',
    description: 'Random Access Memory stores data for active tasks. It is volatile memory. Using two sticks (Dual Channel) significantly improves performance.',
    installation: 'Open the clips on the slots, align the notch on the stick with the slot, and push down until it clicks. Refer to the manual for optimal slot pairing.',
    position: { top: '35%', left: '58%', width: '8%', height: '25%' },
  },
  {
    id: 'gpu',
    name: 'Graphics Card (GPU)',
    description: 'Specialized for rendering images and video. It has its own dedicated memory (VRAM). Connects via high-speed PCIe x16 slots.',
    installation: 'Insert into the top-most PCIe slot. Secure with screws to the case bracket. Most high-end GPUs require 8-pin or 12-pin power cables from the PSU.',
    position: { top: '58%', left: '48%', width: '40%', height: '15%' },
  },
  {
    id: 'psu',
    name: 'Power Supply Unit (PSU)',
    description: 'The "Heart" of the PC. Converts AC wall power to DC. Look for "80 Plus" efficiency ratings (Bronze, Gold, Platinum).',
    installation: 'Typically located at the bottom. The fan should face the vent (usually downwards). Use modular cables to reduce clutter and improve airflow.',
    position: { top: '88%', left: '40%', width: '70%', height: '15%' },
  },
  {
    id: 'storage',
    name: 'Storage (SSD/HDD)',
    description: 'Non-volatile memory for long-term data. NVMe M.2 SSDs are the current standard, offering speeds 10x faster than older SATA SSDs or HDDs.',
    installation: 'M.2 drives screw directly into the motherboard. SATA drives mount in bays and require both a SATA Data cable and a SATA Power cable.',
    position: { top: '82%', left: '78%', width: '15%', height: '10%' },
  },
  {
    id: 'cmos-battery',
    name: 'CMOS Battery (CR2032)',
    description: 'A small coin-cell battery that powers the CMOS chip. This preserves your BIOS settings and system clock even when the PC is unplugged.',
    installation: 'Slides into a small circular slot on the motherboard. If the PC loses time or BIOS settings reset, this battery likely needs replacement.',
    position: { top: '75%', left: '52%', width: '5%', height: '5%' },
  },
  {
    id: 'case-fan',
    name: 'Airflow Management',
    description: 'Intake fans pull cool air in; exhaust fans push hot air out. Proper airflow prevents "thermal throttling" where components slow down to stay cool.',
    installation: 'Mount to the chassis frame. Arrow markings on the fan frame indicate the direction of airflow.',
    position: { top: '35%', left: '15%', width: '10%', height: '15%' },
  },
];

    